### ISSUE TITLE
Upload rawdata from a variable instead of file

### ISSUE THREAD

**Issue by adamgp** [lukeb2014/Dropbox-PHP-SDK-v2#6]
It would be much more convenient to also allow files->upload() to accept a rawdata string for upload rather than having to specify a file path, when generating content on the fly.

Or can you provide an uploadString() function as well?

Thanks

**Comment by lukeb2014** [comment]
I'll add a way so that you can do either this weekend.

**Comment by adamgp** [comment]
Excellent! Thanks. Might want to extend that to the download process so you
can store as file or variable too - if you can't already (haven't checked
sorry)! Makes sense data can come out in the same fashion as it can go
in...?

**Comment by lukeb2014** [comment]
I pushed code changes to a new branch `rawdata`. If you're able to, can you test that code and see if it works for you?

For `files->download()`, I added an optional parameter defaulting to `true` that tells the function whether or not to download the data directly to a file path or not.

For `files->upload()`, I added a `file_exists($file_data)` check to see if the data is a valid file path. If it's not, then the function assumes that it is raw data and treats it as such, otherwise it works the same as before.

If this works for you I'll merge the branches. Thank you.

**Comment by adamgp** [comment]
Thank you. I'll check it out this Thursday when I'm scheduled to work on
the related project. Thanks again!

**Comment by adamgp** [comment]
Confirmed works as expected and falls back to file upload with test script.
Please merge into master at your earliest convenience!

Thank you

-----------

$rawData = time();
$fileName = 'String.txt';

$storePath = '/Directory/' . $fileName;

$dropbox = new Dropbox(COMPANY_DROPBOX_ACCESS_TOKEN);
$dropbox->files->upload($storePath, $rawData, 'overwrite');

**Comment by adamgp** [comment]
With regards to download()

`public function download($path, $target, $output_as_file = true) {`

Could $target double up as the check for whether to output as file? If $target === false then output as raw data else save to the path held in $target? Otherwise to output raw data I have to use it as such:

`$data = $dropbox->files->download('/file/path', null, false);`

Whereas it would be simpler to use as:

`$data = $dropbox->files->download('/file/path', false);`

**Comment by lukeb2014** [comment]
Agreed, I will go ahead and change that.

**Comment by adamgp** [comment]
All works fine downloading to raw data so good to proceed with merging into
master.

**Comment by lukeb2014** [comment]
Merged and published. Thank you for testing this.

**Comment by adamgp** [comment]
No thank you!
